mitre-attack/mitreattack-python

- CHANGELOG.md
- mitreattack/navlayers/exporters/matrix_gen.py
- setup.py
Patch to fix how local cti files are loaded by matrix gen
Addresses #14
> Local CTI patch

- .gitignore
- CHANGELOG.md
- mitreattack/attackToExcel/stixToDf.py
- Adds missing fields to attackToExcel technique output (resolves #17):
- Enterprise: _Impact Type_, _System Requirements_, _Effective Permissions_
- Mobile: __Tactic Type_
- Update gitignore to include additional files (particular macOS files like .DS_Store).
> Add missing fields to stixToDf, update gitignore

- CHANGELOG.md
- mitreattack/attackToExcel/attackToExcel.py
- mitreattack/attackToExcel/stixToDf.py
Adds the ability to filter for platforms to the attackToExcel module.
Addresses #12
> attackToExcel platforms support

- CHANGELOG.md
- README.md
- mitreattack/attackToExcel/attackToExcel.py
- mitreattack/navlayers/core/filter.py
- mitreattack/navlayers/core/gradient.py
- mitreattack/navlayers/core/layer.py
- mitreattack/navlayers/core/layerobj.py
- mitreattack/navlayers/core/layout.py
- mitreattack/navlayers/core/legenditem.py
- mitreattack/navlayers/core/metadata.py
- mitreattack/navlayers/core/technique.py
- mitreattack/navlayers/core/versions.py
- mitreattack/navlayers/exporters/excel_templates.py
- mitreattack/navlayers/exporters/svg_objects.py
- mitreattack/navlayers/exporters/svg_templates.py
- mitreattack/navlayers/exporters/to_excel.py
- mitreattack/navlayers/exporters/to_svg.py
- mitreattack/navlayers/generators/__init__.py
- mitreattack/navlayers/generators/gen_helpers.py
- mitreattack/navlayers/generators/overview_generator.py
- mitreattack/navlayers/generators/usage_generator.py
- mitreattack/navlayers/layerExporter_cli.py
- mitreattack/navlayers/layerGenerator_cli.py
- mitreattack/navlayers/manipulators/layerops.py
Quick patch to prevent the weirdness that can arise if you query the Usage Layer Generator with an ATT&CK Technique ID.
> Generator Patch

- CHANGELOG.md
- README.md
- mitreattack/collections/README.md
- mitreattack/collections/__init__.py
- mitreattack/collections/collection_to_index.py
- mitreattack/navlayers/collections/col_to_index.py
- setup.py
Addresses #28 by adding a CollectionsToIndex module and cli.
> Convert Collections to an Index

- CHANGELOG.md
- README.md
- mitreattack/navlayers/README.md
- mitreattack/navlayers/generators/sum_generator.py
- mitreattack/navlayers/generators/usage_generator.py
- mitreattack/navlayers/layerGenerator_cli.py
Adds the ability to generate sets of layers automatically. 
Closes #21
> Layer Cluster Generation

- CHANGELOG.md
- README.md
- mitreattack/navlayers/README.md
- mitreattack/navlayers/__init__.py
- mitreattack/navlayers/generators/gen_helpers.py
- mitreattack/navlayers/generators/overview_generator.py
- mitreattack/navlayers/generators/sum_generator.py
- mitreattack/navlayers/generators/usage_generator.py
- mitreattack/navlayers/layerGenerator_cli.py
Adds Data Source/Data Component integration to the generator scripts.
Closes #36
> Data Source/Data Component Generator integration

- CHANGELOG.md
- mitreattack/attackToExcel/stixToDf.py
- setup.py
Adds support for multiple CAPEC IDs, and tweaks how permissions get parsed in AttackToExcel.
> Multi-capec

- CHANGELOG.md
- README.md
- mitreattack/navlayers/README.md
- mitreattack/navlayers/core/__init__.py
- mitreattack/navlayers/core/layerobj.py
- mitreattack/navlayers/core/objlink.py
- mitreattack/navlayers/core/technique.py
- mitreattack/navlayers/core/versions.py
Adds support for the 4.3 Layers format, and cleans up a few things along the way.
> First pass at supporting ATT&CK Layers format 4.3

- .gitignore
- CHANGELOG.md
- README.md
- docs/CONTRIBUTING.md
- docs/RELEASE.md
- requirements-dev.txt
Adds documentation for the release process, as well as documentation regarding opportunities for Contribution.
> Documentation

- mitreattack/navlayers/core/gradient.py
- mitreattack/navlayers/core/layerobj.py
- tests/resources/testing_data.py
Patches color and linking issues for the live navigator's version of the 4.3 layer format. 
Addresses #55.
> Color Parsing Patch

- CHANGELOG.md
- mitreattack/collections/collection_to_index.py
- mitreattack/collections/index_to_markdown.py
- mitreattack/collections/stix_to_collection.py
- mitreattack/navlayers/core/gradient.py
- mitreattack/navlayers/core/layer.py
- mitreattack/navlayers/exporters/to_svg.py
- tests/resources/testing_data.py
- tests/test_layers.py
Adds support for 8-hex color within the framework (doesn't render it yet, just supports loading and exporting that data).
Also adds support for unicode-16 text.
Closes #57 and #58
>  Compatibility Update

- mitreattack/navlayers/core/layer.py
> Fix navlayers-layer init bug when passing name and domain arguments

- CHANGELOG.md
- mitreattack/attackToExcel/stixToDf.py
I think this should address the slow-ish Excel exports issue
> Fix #67: Speed up queries for subtechniques

- mitreattack/diffStix/changelog_helper.py
- mitreattack/diffStix/notes.txt
Let me know if this breaks any other related code and I will fix it.
> diff for ICS domain

- setup.py
added "package_data" configuration in setup.py to fix SVG export issue that occurs due to missing font files.
> fixes issue 74

- .gitignore
- CHANGELOG.md
- mitreattack/navlayers/core/layerobj.py
- mitreattack/navlayers/core/objlink.py
- mitreattack/navlayers/core/technique.py
- mitreattack/navlayers/exporters/matrix_gen.py
- mitreattack/navlayers/exporters/svg_objects.py
- mitreattack/navlayers/exporters/svg_templates.py
- mitreattack/navlayers/exporters/to_svg.py
- setup.py
- tests/test_layers.py
> Bug fixes for Navigator module

- mitreattack/attackToExcel/stixToDf.py
Add necessary items to support collection import for workbench:
- Stix ID 
- domain(s)
- first seen, first seen citation, last seen, last seen citation (for campaigns only)
> add objects to excel needed for collection import in workbench

- mitreattack/navlayers/core/versions.py
- mitreattack/navlayers/exporters/excel_templates.py
- mitreattack/navlayers/exporters/matrix_gen.py
- mitreattack/navlayers/exporters/svg_templates.py
Summary of changes
- Fix the SVG and Excel generator code to build the ICS Matrix
- Upgrade Navigator layer version to 4.4
> Fix SVG/Excel builders for ICS and upgrade Navigator layer version

- .sonarcloud.properties
Hi mitreattack-python team! 
Please review a small PR aiming to update sonarcloud properties file:
- Remove Python versions 3.6, 3.7 (deprecated versions)
- Add Python 3.11
Thank you!
> Update sonarcloud properties file

- mitreattack/navlayers/core/README.md
- mitreattack/navlayers/core/layerobj.py
- mitreattack/navlayers/core/layout.py
- mitreattack/navlayers/core/versions.py
- tests/resources/testing_data.py
Update Layer File Format version to 4.5 in support of the upcoming 4.9.0 Navigator release
Resolves #98
> 98 update layer version to 4.5

- mitreattack/navlayers/README.md
- mitreattack/navlayers/exporters/svg_objects.py
- mitreattack/navlayers/exporters/svg_templates.py
- mitreattack/navlayers/exporters/to_svg.py
> add font size parameter to svg config

- CHANGELOG.md
- docs/mitre_attack_data/examples.rst
- examples/get_procedure_examples_by_technique.py
- mitreattack/stix20/MitreAttackData.py
Added functionality to `MitreAttackData` to retrieve a list of Procedure Examples by technique id
> get procedure examples by technique

- CHANGELOG.md
- mitreattack/navlayers/manipulators/layerops.py
> Fix false warnings during layer ops
